=== skyrising/mc-versions/data/schemas/version.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://skyrising.github.io/mc-versions/schemas/version.json",
    "$defs": {
        "version": {
            "description": "A version in the Omniarchive format",
            "type": "string",
            "pattern": "^(((server-)?([abc]|inf?-|rd-|af-)?[0-9]+[.0-9]*)|[0-9]{2}w[0-9]{2}[a-z~])a?([_-][0-9a-z]+)*$"
        },
        "semver": {
            "description": "A version number in SemVer format (see https://semver.org/ for the specification)",
            "type": "string",
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        },
        "releaseType": {
            "description": "A release type (e.g. release, snapshot, etc.)",
            "type": "string",
            "pattern": "^[a-z_]+$",
            "examples": ["release", "snapshot", "old_alpha", "old_beta"]
        },
        "sha1": {
            "description": "The SHA-1 hash of a file",
            "type": "string",
            "pattern": "^[0-9a-f]{40}$"
        },
        "downloadInfo": {
            "type": "object",
            "properties": {
                "sha1": {"$ref": "#/$defs/sha1"},
                "size": {"type": "integer", "minimum": 0},
                "url": {"type": "string", "format": "uri"}
            },
            "additionalProperties": false
        },
        "protocolVersion": {
            "type": "object",
            "properties": {
                "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                "version": {"type": "integer", "minimum": 0}
            },
            "required": ["type", "version"],
            "additionalProperties": false
        },
        "worldFormat": {
            "type": "object",
            "properties": {
                "format": {"enum": ["alpha", "region", "anvil"]},
                "version": {"type": "integer"}
            },
            "required": ["format"],
            "additionalProperties": false
        },
        "manifestInfo": {
            "type": "object",
            "properties": {
                "assetHash": {"$ref": "#/$defs/sha1"},
                "assetIndex": {"type": "string"},
                "downloads": {"$ref": "#/$defs/sha1"},
                "downloadsId": {"type": "integer", "minimum": 1},
                "hash": {"$ref": "#/$defs/sha1"},
                "time": {"type": "string", "format": "date-time"},
                "type": {"$ref": "#/$defs/releaseType"},
                "url": {"type": "string", "format": "uri-reference"}
            }
        }
    },
    "type": "object",
    "properties": {
        "id": {"$ref": "#/$defs/version"},
        "client": {
            "type": "boolean",
            "description": "Whether `downloads` includes a client"
        },
        "server": {
            "type": "boolean",
            "description": "Whether `downloads` includes a server"
        },
        "sharedMappings": {
            "type": "boolean",
            "description": "Whether the obfuscation mappings for client and server are the same"
        },
        "downloads": {
            "patternProperties": {
                "^[a-z_]*$": {"$ref": "#/$defs/downloadInfo"}
            },
            "additionalProperties": false
        },
        "manifests": {
            "type": "array",
            "items": {"$ref": "#/$defs/manifestInfo"}
        },
        "normalizedVersion": {"$ref": "#/$defs/semver"},
        "previous": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "next": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "releaseTarget": {"$ref": "#/$defs/semver"},
        "releaseTime": {"type": "string", "format": "date-time"},
        "protocol": {
            "oneOf": [{
                "type": "object",
                "properties": {
                    "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                    "version": {"type": "integer", "minimum": 0}
                },
                "required": ["type", "version"],
                "additionalProperties": false
            }, {
                "type": "null"
            }]
        },
        "world": {"$ref": "#/$defs/worldFormat"}
    },
    "required": ["id", "client", "server", "downloads", "normalizedVersion", "previous", "next", "releaseTarget", "releaseTime", "protocol", "world"]
}

=== skyrising/mc-versions/data/version/13w04a.json
{
  "client": true,
  "downloads": {
    "client": {
      "sha1": "dff06285694aab7771682f949d51bca98ce52359",
      "size": 6426112,
      "url": "https://assets.minecraft.net/13w04a/minecraft.jar"
    },
    "server": {
      "sha1": "023471451daaadaf2679817130ec740d050110fb",
      "size": 2211840,
      "url": "https://assets.minecraft.net/13w04a/minecraft_server.jar"
    },
    "windows_server": {
      "sha1": "f2b934b3995baeacdb62378fbf5f83ff3be4f79e",
      "size": 2393088,
      "url": "https://assets.minecraft.net/13w04a/Minecraft_Server.exe"
    }
  },
  "id": "13w04a",
  "manifests": [
    {
      "assetHash": "4759bad2824e419da9db32861fcdc3a274336532",
      "assetIndex": "pre-1.6",
      "downloads": "2dc6aff648a34464cc19b988c8b0bd3402add9eb",
      "downloadsId": 1,
      "hash": "7f3eac30f5dd4473cdf6d82cf8a1ee56c729ac85",
      "time": "2013-01-24T14:17:50+00:00",
      "type": "snapshot",
      "url": "../manifest/7/f/3eac30f5dd4473cdf6d82cf8a1ee56c729ac85/13w04a.json"
    }
  ],
  "next": [
    "13w05a"
  ],
  "normalizedVersion": "1.5.0-alpha.13.4.a",
  "previous": [
    "13w03a"
  ],
  "protocol": {
    "type": "modern",
    "version": 55
  },
  "releaseTarget": "1.5",
  "releaseTime": "2013-01-24T14:17:50+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== skyrising/mc-versions/data/version/1.5.2-pre-250903.json
{
  "client": true,
  "downloads": {
    "client": {
      "sha1": "ca3b2e326f463a55895e5bbe993c64d6d4149dd2",
      "size": 5564656,
      "url": "https://files.betacraft.pl/launcher/assets/versions/1.5.2-pre-1.jar"
    },
    "server": {
      "sha1": "f9ae3f651319151ce99a0bfad6b34fa16eb6775f",
      "size": 2360903,
      "url": "https://launcher.mojang.com/v1/objects/f9ae3f651319151ce99a0bfad6b34fa16eb6775f/server.jar"
    },
    "windows_server": {
      "sha1": "49fded489aae76e012048c3c81dcc323384ef781",
      "size": 2542151,
      "url": "https://launcher.mojang.com/v1/objects/49fded489aae76e012048c3c81dcc323384ef781/windows_server.exe"
    }
  },
  "id": "1.5.2-pre-250903",
  "manifests": [
    {
      "assetHash": "770572e819335b6c0a053f8378ad88eda189fc14",
      "assetIndex": "legacy",
      "downloads": "ce4e752bf45d5fdeb9c645a74ade3ed5ed1882bb",
      "downloadsId": 1,
      "hash": "aee2438bbd015a8039e550f4b4284d5a14cc3ba1",
      "time": "2013-04-25T15:45:00+00:00",
      "type": "release",
      "url": "../manifest/a/e/e2438bbd015a8039e550f4b4284d5a14cc3ba1/1.5.2-pre-04260937.json"
    }
  ],
  "next": [
    "1.5.2"
  ],
  "normalizedVersion": "1.5.2-pre+250903",
  "previous": [
    "1.5.1"
  ],
  "protocol": {
    "type": "modern",
    "version": 61
  },
  "releaseTarget": "1.5.2",
  "releaseTime": "2013-04-25T15:45:00+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== skyrising/mc-versions/data/version/20w12a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "8ffb3d6807ede557ca7e114b4b6c3fb797d6e432",
      "size": 16049329,
      "url": "https://launcher.mojang.com/v1/objects/8ffb3d6807ede557ca7e114b4b6c3fb797d6e432/client.jar"
    },
    "client_mappings": {
      "sha1": "3ddfd87b8b995611a078dc8742b2383d82784d8a",
      "size": 5177618,
      "url": "https://launcher.mojang.com/v1/objects/3ddfd87b8b995611a078dc8742b2383d82784d8a/client.txt"
    },
    "server": {
      "sha1": "3d9657a172415a163e25096942f5a4d110b984a0",
      "size": 36538897,
      "url": "https://launcher.mojang.com/v1/objects/3d9657a172415a163e25096942f5a4d110b984a0/server.jar"
    },
    "server_mappings": {
      "sha1": "1a0824596acf68312f70522a164508dd037a9415",
      "size": 3992275,
      "url": "https://launcher.mojang.com/v1/objects/1a0824596acf68312f70522a164508dd037a9415/server.txt"
    }
  },
  "id": "20w12a",
  "manifests": [
    {
      "assetHash": "28680197f74e5e1d55054f6a63509c8298d428f9",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "aa2a18d99b7e7c967b7100691e26609fe62aded5",
      "lastModified": "2022-02-25T13:39:39+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/a/a/2a18d99b7e7c967b7100691e26609fe62aded5/20w12a.json"
    },
    {
      "assetHash": "738b17ea266089b5e384791eb5a2cf1fafe109b6",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "c7ddf0ddc730010cf46c04a0b1d7027f64dfaa75",
      "lastModified": "2021-12-15T15:52:42+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/c/7/ddf0ddc730010cf46c04a0b1d7027f64dfaa75/20w12a.json"
    },
    {
      "assetHash": "738b17ea266089b5e384791eb5a2cf1fafe109b6",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "55d7f8dbd0cf746135eb8cbc7f5c59e6a4d85a34",
      "lastModified": "2021-12-10T02:59:01+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/5/5/d7f8dbd0cf746135eb8cbc7f5c59e6a4d85a34/20w12a.json"
    },
    {
      "assetHash": "738b17ea266089b5e384791eb5a2cf1fafe109b6",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "a1e87a0266cb3cffcc58fe6611daa3e800af053a",
      "lastModified": "2021-11-30T09:49:25+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/a/1/e87a0266cb3cffcc58fe6611daa3e800af053a/20w12a.json"
    },
    {
      "assetHash": "ad75fb46ff5c89aa5f9c90e12481e963854f9a6e",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "2b5a8457de3ebf77a2765ce0167202c40f768b0d",
      "lastModified": "2021-07-07T13:56:37+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/2/b/5a8457de3ebf77a2765ce0167202c40f768b0d/20w12a.json"
    },
    {
      "assetHash": "ad75fb46ff5c89aa5f9c90e12481e963854f9a6e",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "a76f3ae281981256620d813082cfdcbf4ad7c13f",
      "lastModified": "2021-06-29T15:20:55+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/a/7/6f3ae281981256620d813082cfdcbf4ad7c13f/20w12a.json"
    },
    {
      "assetHash": "3a5d110a6ab102c7083bae4296d2de4b8fcf92eb",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "ee1b956ec5d4861cb92a5e65481ec7c8a091cf42",
      "lastModified": "2021-01-13T14:12:54+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/e/e/1b956ec5d4861cb92a5e65481ec7c8a091cf42/20w12a.json"
    },
    {
      "assetHash": "f8e11ca03b475dd655755b945334c7a0ac2c3b43",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "502345f3d68f7bacab0b0ec02780d77f81a69bfe",
      "lastModified": "2020-12-02T16:57:45+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/5/0/2345f3d68f7bacab0b0ec02780d77f81a69bfe/20w12a.json"
    },
    {
      "assetHash": "6aeb80664ca8c3c1e114f9ee428bb0bd7d29b1ab",
      "assetIndex": "1.16",
      "downloads": "1ad9f7180923ded95963e08362660ee73f63b20d",
      "downloadsId": 1,
      "hash": "01293675d5b48888c02231f1a954a54227686db0",
      "lastModified": "2020-11-02T16:34:12+00:00",
      "time": "2020-03-18T16:42:06+00:00",
      "type": "snapshot",
      "url": "../manifest/0/1/293675d5b48888c02231f1a954a54227686db0/20w12a.json"
    }
  ],
  "next": [
    "20w13a"
  ],
  "normalizedVersion": "1.16.0-alpha.20.12.a",
  "previous": [
    "20w11a"
  ],
  "protocol": {
    "type": "netty",
    "version": 707
  },
  "releaseTarget": "1.16",
  "releaseTime": "2020-03-18T16:42:06+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 2515
  }
}

=== skyrising/mc-versions/data/version/17w16b.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "339b2099d66421af8f194e76074ebda5694abdb3",
      "size": 10039579,
      "url": "https://launcher.mojang.com/v1/objects/339b2099d66421af8f194e76074ebda5694abdb3/client.jar"
    },
    "server": {
      "sha1": "80601961e590046727791d6b18f51d840ea86e1c",
      "size": 30106756,
      "url": "https://launcher.mojang.com/v1/objects/80601961e590046727791d6b18f51d840ea86e1c/server.jar"
    }
  },
  "id": "17w16b",
  "manifests": [
    {
      "assetHash": "1584b57c1a0b5e593fad1f5b8f78536ca640547b",
      "assetIndex": "1.12",
      "downloads": "514dca58ab10ed75cb8e92519c415fdf04391fe1",
      "downloadsId": 1,
      "hash": "e89edd2e77733aeb33f66153a9fe303baa410c5f",
      "lastModified": "2021-12-15T15:57:07+00:00",
      "time": "2017-04-21T12:02:59+00:00",
      "type": "snapshot",
      "url": "../manifest/e/8/9edd2e77733aeb33f66153a9fe303baa410c5f/17w16b.json"
    },
    {
      "assetHash": "1584b57c1a0b5e593fad1f5b8f78536ca640547b",
      "assetIndex": "1.12",
      "downloads": "514dca58ab10ed75cb8e92519c415fdf04391fe1",
      "downloadsId": 1,
      "hash": "305f3ed331c4e9d7bce561ad6f239f6162b3b0fb",
      "lastModified": "2021-12-10T03:03:05+00:00",
      "time": "2017-04-21T12:02:59+00:00",
      "type": "snapshot",
      "url": "../manifest/3/0/5f3ed331c4e9d7bce561ad6f239f6162b3b0fb/17w16b.json"
    },
    {
      "assetHash": "1584b57c1a0b5e593fad1f5b8f78536ca640547b",
      "assetIndex": "1.12",
      "downloads": "514dca58ab10ed75cb8e92519c415fdf04391fe1",
      "downloadsId": 1,
      "hash": "3cd2889c6bc62ea2dbe150a93d4e1bcec0946244",
      "lastModified": "2021-07-07T14:00:39+00:00",
      "time": "2017-04-21T12:02:59+00:00",
      "type": "snapshot",
      "url": "../manifest/3/c/d2889c6bc62ea2dbe150a93d4e1bcec0946244/17w16b.json"
    },
    {
      "assetHash": "1584b57c1a0b5e593fad1f5b8f78536ca640547b",
      "assetIndex": "1.12",
      "downloads": "514dca58ab10ed75cb8e92519c415fdf04391fe1",
      "downloadsId": 1,
      "hash": "87db96e70f2a6bfd4e474983194ea31411009ab6",
      "lastModified": "2018-08-29T12:59:46+00:00",
      "time": "2017-04-21T12:02:59+00:00",
      "type": "snapshot",
      "url": "../manifest/8/7/db96e70f2a6bfd4e474983194ea31411009ab6/17w16b.json"
    }
  ],
  "next": [
    "17w17a"
  ],
  "normalizedVersion": "1.12.0-alpha.17.16.b",
  "previous": [
    "17w16a"
  ],
  "protocol": {
    "type": "netty",
    "version": 323
  },
  "releaseTarget": "1.12",
  "releaseTime": "2017-04-21T12:02:59+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1127
  }
}

=== skyrising/mc-versions/data/version/13w26a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "b9a5d053016efa035f1b424625e0fd4736ac2dd6",
      "size": 4718211,
      "url": "https://launcher.mojang.com/v1/objects/b9a5d053016efa035f1b424625e0fd4736ac2dd6/client.jar"
    },
    "server": {
      "sha1": "bafe11faf3419c8813beb948e353912239d50bc1",
      "size": 7183838,
      "url": "https://launcher.mojang.com/v1/objects/bafe11faf3419c8813beb948e353912239d50bc1/server.jar"
    },
    "windows_server": {
      "sha1": "fc3bf59fce8a5a2bc3b871559d3b8bb9035cec36",
      "size": 7579614,
      "url": "https://launcher.mojang.com/v1/objects/fc3bf59fce8a5a2bc3b871559d3b8bb9035cec36/windows_server.exe"
    }
  },
  "id": "13w26a",
  "manifests": [
    {
      "assetHash": "770572e819335b6c0a053f8378ad88eda189fc14",
      "assetIndex": "legacy",
      "downloads": "671104a91c6733acbf03cba4deebbdd8cfbdeef8",
      "downloadsId": 1,
      "hash": "7ee9e11660839f2f413b8d5bf9d5d70b42dc5791",
      "lastModified": "2018-08-29T13:02:41+00:00",
      "time": "2013-06-24T16:06:06+00:00",
      "type": "snapshot",
      "url": "../manifest/7/e/e9e11660839f2f413b8d5bf9d5d70b42dc5791/13w26a.json"
    }
  ],
  "next": [
    "1.6-pre-06251516"
  ],
  "normalizedVersion": "1.6.0-alpha.13.26.a",
  "previous": [
    "13w25c"
  ],
  "protocol": {
    "type": "modern",
    "version": 72
  },
  "releaseTarget": "1.6",
  "releaseTime": "2013-06-24T16:06:06+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}
