=== skyrising/mc-versions/data/schemas/version.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://skyrising.github.io/mc-versions/schemas/version.json",
    "$defs": {
        "version": {
            "description": "A version in the Omniarchive format",
            "type": "string",
            "pattern": "^(((server-)?([abc]|inf?-|rd-|af-)?[0-9]+[.0-9]*)|[0-9]{2}w[0-9]{2}[a-z~])a?([_-][0-9a-z]+)*$"
        },
        "semver": {
            "description": "A version number in SemVer format (see https://semver.org/ for the specification)",
            "type": "string",
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        },
        "releaseType": {
            "description": "A release type (e.g. release, snapshot, etc.)",
            "type": "string",
            "pattern": "^[a-z_]+$",
            "examples": ["release", "snapshot", "old_alpha", "old_beta"]
        },
        "sha1": {
            "description": "The SHA-1 hash of a file",
            "type": "string",
            "pattern": "^[0-9a-f]{40}$"
        },
        "downloadInfo": {
            "type": "object",
            "properties": {
                "sha1": {"$ref": "#/$defs/sha1"},
                "size": {"type": "integer", "minimum": 0},
                "url": {"type": "string", "format": "uri"}
            },
            "additionalProperties": false
        },
        "protocolVersion": {
            "type": "object",
            "properties": {
                "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                "version": {"type": "integer", "minimum": 0}
            },
            "required": ["type", "version"],
            "additionalProperties": false
        },
        "worldFormat": {
            "type": "object",
            "properties": {
                "format": {"enum": ["alpha", "region", "anvil"]},
                "version": {"type": "integer"}
            },
            "required": ["format"],
            "additionalProperties": false
        },
        "manifestInfo": {
            "type": "object",
            "properties": {
                "assetHash": {"$ref": "#/$defs/sha1"},
                "assetIndex": {"type": "string"},
                "downloads": {"$ref": "#/$defs/sha1"},
                "downloadsId": {"type": "integer", "minimum": 1},
                "hash": {"$ref": "#/$defs/sha1"},
                "time": {"type": "string", "format": "date-time"},
                "type": {"$ref": "#/$defs/releaseType"},
                "url": {"type": "string", "format": "uri-reference"}
            }
        }
    },
    "type": "object",
    "properties": {
        "id": {"$ref": "#/$defs/version"},
        "client": {
            "type": "boolean",
            "description": "Whether `downloads` includes a client"
        },
        "server": {
            "type": "boolean",
            "description": "Whether `downloads` includes a server"
        },
        "sharedMappings": {
            "type": "boolean",
            "description": "Whether the obfuscation mappings for client and server are the same"
        },
        "downloads": {
            "patternProperties": {
                "^[a-z_]*$": {"$ref": "#/$defs/downloadInfo"}
            },
            "additionalProperties": false
        },
        "manifests": {
            "type": "array",
            "items": {"$ref": "#/$defs/manifestInfo"}
        },
        "normalizedVersion": {"$ref": "#/$defs/semver"},
        "previous": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "next": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "releaseTarget": {"$ref": "#/$defs/semver"},
        "releaseTime": {"type": "string", "format": "date-time"},
        "protocol": {
            "oneOf": [{
                "type": "object",
                "properties": {
                    "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                    "version": {"type": "integer", "minimum": 0}
                },
                "required": ["type", "version"],
                "additionalProperties": false
            }, {
                "type": "null"
            }]
        },
        "world": {"$ref": "#/$defs/worldFormat"}
    },
    "required": ["id", "client", "server", "downloads", "normalizedVersion", "previous", "next", "releaseTarget", "releaseTime", "protocol", "world"]
}

=== skyrising/mc-versions/data/version/1.7.10-pre3.json
{
  "client": true,
  "downloads": {
    "client": {
      "sha1": "9e3d4d71e9827fa2024ec90c065b2120ba80a024",
      "size": 5314833,
      "url": "https://launcher.mojang.com/v1/objects/9e3d4d71e9827fa2024ec90c065b2120ba80a024/client.jar"
    },
    "server": {
      "sha1": "b9fdcbd17407d9eaeedcf4ff79b3121ee40133db",
      "size": 9606901,
      "url": "https://launcher.mojang.com/v1/objects/b9fdcbd17407d9eaeedcf4ff79b3121ee40133db/server.jar"
    },
    "windows_server": {
      "sha1": "267c1456c63485f1b91fd3504795e18799c3a404",
      "size": 10001141,
      "url": "https://launcher.mojang.com/v1/objects/267c1456c63485f1b91fd3504795e18799c3a404/windows_server.exe"
    }
  },
  "id": "1.7.10-pre3",
  "manifests": [
    {
      "assetHash": "545510a60f526b9aa8a38f9c0bc7a74235d21675",
      "assetIndex": "1.7.4",
      "downloads": "6a19d62a6983f787b8f66199f3ce1b50eb6726c4",
      "downloadsId": 1,
      "hash": "0c27e44e9f9350fe76a0ac48da5563a89513442b",
      "lastModified": "2021-12-15T16:00:46+00:00",
      "time": "2014-05-14T15:29:23+00:00",
      "type": "snapshot",
      "url": "../manifest/0/c/27e44e9f9350fe76a0ac48da5563a89513442b/1.7.10-pre3.json"
    },
    {
      "assetHash": "545510a60f526b9aa8a38f9c0bc7a74235d21675",
      "assetIndex": "1.7.4",
      "downloads": "6a19d62a6983f787b8f66199f3ce1b50eb6726c4",
      "downloadsId": 1,
      "hash": "5e772dee3ad034349a0d98da06c110df54b530a3",
      "lastModified": "2021-07-07T14:04:00+00:00",
      "time": "2014-05-14T15:29:23+00:00",
      "type": "snapshot",
      "url": "../manifest/5/e/772dee3ad034349a0d98da06c110df54b530a3/1.7.10-pre3.json"
    },
    {
      "assetHash": "545510a60f526b9aa8a38f9c0bc7a74235d21675",
      "assetIndex": "1.7.4",
      "downloads": "6a19d62a6983f787b8f66199f3ce1b50eb6726c4",
      "downloadsId": 1,
      "hash": "37da9a5fdf915ebeb294439f31051791a39102fd",
      "lastModified": "2018-08-29T13:02:02+00:00",
      "time": "2014-05-14T15:29:23+00:00",
      "type": "snapshot",
      "url": "../manifest/3/7/da9a5fdf915ebeb294439f31051791a39102fd/1.7.10-pre3.json"
    }
  ],
  "next": [
    "1.7.10-pre4"
  ],
  "normalizedVersion": "1.7.10-pre.3",
  "previous": [
    "1.7.10-pre2"
  ],
  "protocol": {
    "type": "netty",
    "version": 5
  },
  "releaseTarget": "1.7.10",
  "releaseTime": "2014-06-10T00:00:00+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== skyrising/mc-versions/data/version/18w06a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "78ed8d3359453614d8f69bd982111e8aa6c8f612",
      "size": 11163926,
      "url": "https://launcher.mojang.com/v1/objects/78ed8d3359453614d8f69bd982111e8aa6c8f612/client.jar"
    },
    "server": {
      "sha1": "4e47158fd42d966884a7ffb7440b35d86c038049",
      "size": 31117130,
      "url": "https://launcher.mojang.com/v1/objects/4e47158fd42d966884a7ffb7440b35d86c038049/server.jar"
    }
  },
  "id": "18w06a",
  "manifests": [
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "510c548ea983b80d76b0ae112c209865fdd8d7ff",
      "downloadsId": 1,
      "hash": "cbf797f54c85ca183be91b7879f95e46b402f7db",
      "time": "2018-02-09T12:09:55+00:00",
      "type": "snapshot",
      "url": "../manifest/c/b/f797f54c85ca183be91b7879f95e46b402f7db/18w06a.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "510c548ea983b80d76b0ae112c209865fdd8d7ff",
      "downloadsId": 1,
      "hash": "9a1741a1f4c3d0030aed23d5766539a806052cc3",
      "time": "2018-02-09T12:09:55+00:00",
      "type": "snapshot",
      "url": "../manifest/9/a/1741a1f4c3d0030aed23d5766539a806052cc3/18w06a.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "510c548ea983b80d76b0ae112c209865fdd8d7ff",
      "downloadsId": 1,
      "hash": "8b46d50661a17a22ecb5166f6822fb94ed1dc2c9",
      "time": "2018-02-09T12:09:55+00:00",
      "type": "snapshot",
      "url": "../manifest/8/b/46d50661a17a22ecb5166f6822fb94ed1dc2c9/18w06a.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "510c548ea983b80d76b0ae112c209865fdd8d7ff",
      "downloadsId": 1,
      "hash": "356ebf067ef74aa437bd9849ebb2dd36df7ab54b",
      "time": "2018-02-09T12:09:55+00:00",
      "type": "snapshot",
      "url": "../manifest/3/5/6ebf067ef74aa437bd9849ebb2dd36df7ab54b/18w06a.json"
    }
  ],
  "next": [
    "18w07a"
  ],
  "normalizedVersion": "1.13.0-alpha.18.6.a",
  "previous": [
    "18w05a"
  ],
  "protocol": {
    "type": "netty",
    "version": 357
  },
  "releaseTarget": "1.13",
  "releaseTime": "2018-02-09T12:09:55+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1466
  }
}

=== skyrising/mc-versions/data/version/18w14b.json
{
  "client": true,
  "downloads": {
    "client": {
      "sha1": "d9b4fc98eb5242346ed0421f6ccd3c9032dc0514",
      "size": 11838478,
      "url": "https://launcher.mojang.com/v1/objects/d9b4fc98eb5242346ed0421f6ccd3c9032dc0514/client.jar"
    },
    "server": {
      "sha1": "85d6445fc4596e6b69fb00f0d3e5462dfeeb933c",
      "size": 31534189,
      "url": "https://launcher.mojang.com/v1/objects/85d6445fc4596e6b69fb00f0d3e5462dfeeb933c/server.jar"
    }
  },
  "id": "18w14b",
  "manifests": [
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "2fcc4f9f749990434ddd23fe92785c1596cc8a8c",
      "downloadsId": 1,
      "hash": "4cafabaf5351a4df5d398b60fbd99c310b1671ec",
      "lastModified": "2021-12-15T15:56:01+00:00",
      "time": "2018-04-05T14:44:02+00:00",
      "type": "snapshot",
      "url": "../manifest/4/c/afabaf5351a4df5d398b60fbd99c310b1671ec/18w14b.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "2fcc4f9f749990434ddd23fe92785c1596cc8a8c",
      "downloadsId": 1,
      "hash": "b1a318d1d40fa24283e0eeb1ab42b9a9f6251709",
      "lastModified": "2021-12-10T03:02:04+00:00",
      "time": "2018-04-05T14:44:02+00:00",
      "type": "snapshot",
      "url": "../manifest/b/1/a318d1d40fa24283e0eeb1ab42b9a9f6251709/18w14b.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "2fcc4f9f749990434ddd23fe92785c1596cc8a8c",
      "downloadsId": 1,
      "hash": "9c7b593ae032fca813c6c81feb25fce1d64be5f6",
      "lastModified": "2021-07-07T13:59:39+00:00",
      "time": "2018-04-05T14:44:02+00:00",
      "type": "snapshot",
      "url": "../manifest/9/c/7b593ae032fca813c6c81feb25fce1d64be5f6/18w14b.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "2fcc4f9f749990434ddd23fe92785c1596cc8a8c",
      "downloadsId": 1,
      "hash": "baf7f6dab46c6678111137baa9431c7e278ea5c8",
      "lastModified": "2018-08-29T12:59:04+00:00",
      "time": "2018-04-05T14:44:02+00:00",
      "type": "snapshot",
      "url": "../manifest/b/a/f7f6dab46c6678111137baa9431c7e278ea5c8/18w14b.json"
    }
  ],
  "next": [
    "18w15a"
  ],
  "normalizedVersion": "1.13.0-alpha.18.14.b",
  "previous": [
    "18w14a"
  ],
  "protocol": {
    "type": "netty",
    "version": 370
  },
  "releaseTarget": "1.13",
  "releaseTime": "2018-04-05T14:44:02+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1481
  }
}

=== skyrising/mc-versions/data/version/1.13-pre10.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "72c4fbff2a1318a57bfb66e325055064a13378a8",
      "size": 16031164,
      "url": "https://launcher.mojang.com/v1/objects/72c4fbff2a1318a57bfb66e325055064a13378a8/client.jar"
    },
    "server": {
      "sha1": "2ffcae7a9489d515b0f733430923ef974dffd56b",
      "size": 32642829,
      "url": "https://launcher.mojang.com/v1/objects/2ffcae7a9489d515b0f733430923ef974dffd56b/server.jar"
    }
  },
  "id": "1.13-pre10",
  "manifests": [
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "826e6eb882196b7c7359611ea9e9f03594a51e23",
      "downloadsId": 1,
      "hash": "89a639b68be27cbe45c6ced76709f9fc45587108",
      "time": "2018-07-17T14:48:06+00:00",
      "type": "snapshot",
      "url": "../manifest/8/9/a639b68be27cbe45c6ced76709f9fc45587108/1.13-pre10.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "826e6eb882196b7c7359611ea9e9f03594a51e23",
      "downloadsId": 1,
      "hash": "7f30e477206515105544b66213b254ccab74706e",
      "time": "2018-07-17T14:48:06+00:00",
      "type": "snapshot",
      "url": "../manifest/7/f/30e477206515105544b66213b254ccab74706e/1.13-pre10.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "826e6eb882196b7c7359611ea9e9f03594a51e23",
      "downloadsId": 1,
      "hash": "3cdff1f50c26eb83666f7ee35f7624c236bc7124",
      "time": "2018-07-17T14:48:06+00:00",
      "type": "snapshot",
      "url": "../manifest/3/c/dff1f50c26eb83666f7ee35f7624c236bc7124/1.13-pre10.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "826e6eb882196b7c7359611ea9e9f03594a51e23",
      "downloadsId": 1,
      "hash": "19f5b3ba211fbe9649f8cde8294a62ac86925655",
      "time": "2018-07-17T14:48:06+00:00",
      "type": "snapshot",
      "url": "../manifest/1/9/f5b3ba211fbe9649f8cde8294a62ac86925655/1.13-pre10.json"
    }
  ],
  "next": [
    "1.13"
  ],
  "normalizedVersion": "1.13.0-pre.10",
  "previous": [
    "1.13-pre9"
  ],
  "protocol": {
    "type": "netty",
    "version": 392
  },
  "releaseTarget": "1.13",
  "releaseTime": "2018-07-17T14:48:06+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1518
  }
}

=== skyrising/mc-versions/data/version/18w43c.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "a040369aa294a5a42048d828b03592b54db6a8d3",
      "size": 16870823,
      "url": "https://launcher.mojang.com/v1/objects/a040369aa294a5a42048d828b03592b54db6a8d3/client.jar"
    },
    "server": {
      "sha1": "b2dc0522b0802cbb8e81d1afd3e46be8819d3c1d",
      "size": 34477549,
      "url": "https://launcher.mojang.com/v1/objects/b2dc0522b0802cbb8e81d1afd3e46be8819d3c1d/server.jar"
    }
  },
  "id": "18w43c",
  "manifests": [
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "dbd1df61f8c1f4647414da08f139279dbf674fe1",
      "downloadsId": 1,
      "hash": "f5ed0e423941499ade98c9fda9c9d73fe70dff4a",
      "time": "2018-10-26T08:40:46+00:00",
      "type": "snapshot",
      "url": "../manifest/f/5/ed0e423941499ade98c9fda9c9d73fe70dff4a/18w43c.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "dbd1df61f8c1f4647414da08f139279dbf674fe1",
      "downloadsId": 1,
      "hash": "cd658b49a18648e6ea9c56c311372151ca03e191",
      "time": "2018-10-26T08:40:46+00:00",
      "type": "snapshot",
      "url": "../manifest/c/d/658b49a18648e6ea9c56c311372151ca03e191/18w43c.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "dbd1df61f8c1f4647414da08f139279dbf674fe1",
      "downloadsId": 1,
      "hash": "c5adfd2fc8a0ca78975e16ede557d8c2e321929d",
      "time": "2018-10-26T08:40:46+00:00",
      "type": "snapshot",
      "url": "../manifest/c/5/adfd2fc8a0ca78975e16ede557d8c2e321929d/18w43c.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "dbd1df61f8c1f4647414da08f139279dbf674fe1",
      "downloadsId": 1,
      "hash": "5adf5d66e2a6e459e784d31aea61bf024da7101b",
      "time": "2018-10-26T08:40:46+00:00",
      "type": "snapshot",
      "url": "../manifest/5/a/df5d66e2a6e459e784d31aea61bf024da7101b/18w43c.json"
    }
  ],
  "next": [
    "18w44a"
  ],
  "normalizedVersion": "1.14.0-alpha.18.43.c",
  "previous": [
    "18w43b"
  ],
  "protocol": {
    "type": "netty",
    "version": 442
  },
  "releaseTarget": "1.14",
  "releaseTime": "2018-10-26T08:40:46+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1903
  }
}

=== skyrising/mc-versions/data/version/1.13-pre6.json
{
  "client": true,
  "downloads": {
    "client": {
      "sha1": "9405570c459c0803da2754b34e5ffeb74413a904",
      "size": 15911764,
      "url": "https://launcher.mojang.com/v1/objects/9405570c459c0803da2754b34e5ffeb74413a904/client.jar"
    },
    "server": {
      "sha1": "71a2f9a760f0cbcf09d1eae60eebe1ccbb7ea1db",
      "size": 32612139,
      "url": "https://launcher.mojang.com/v1/objects/71a2f9a760f0cbcf09d1eae60eebe1ccbb7ea1db/server.jar"
    }
  },
  "id": "1.13-pre6",
  "manifests": [
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4242c9a02bcc79aebb15be0216d7fe4394123ed6",
      "downloadsId": 1,
      "hash": "873e32dca9d8c8350a7429ed46ac4418704351a2",
      "lastModified": "2021-12-15T15:55:36+00:00",
      "time": "2018-07-04T12:36:00+00:00",
      "type": "snapshot",
      "url": "../manifest/8/7/3e32dca9d8c8350a7429ed46ac4418704351a2/1.13-pre6.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4242c9a02bcc79aebb15be0216d7fe4394123ed6",
      "downloadsId": 1,
      "hash": "4b1f6e21d27350ebc98150511f11fd2ec7c63f8f",
      "lastModified": "2021-12-10T03:01:41+00:00",
      "time": "2018-07-04T12:36:00+00:00",
      "type": "snapshot",
      "url": "../manifest/4/b/1f6e21d27350ebc98150511f11fd2ec7c63f8f/1.13-pre6.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4242c9a02bcc79aebb15be0216d7fe4394123ed6",
      "downloadsId": 1,
      "hash": "e9b6efae99cf732242ae0cbdb5003dd555a2df40",
      "lastModified": "2021-07-07T13:59:16+00:00",
      "time": "2018-07-04T12:36:00+00:00",
      "type": "snapshot",
      "url": "../manifest/e/9/b6efae99cf732242ae0cbdb5003dd555a2df40/1.13-pre6.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4242c9a02bcc79aebb15be0216d7fe4394123ed6",
      "downloadsId": 1,
      "hash": "f1c6758e1219e212993f5db422100bca4eb68818",
      "lastModified": "2018-08-29T12:58:48+00:00",
      "time": "2018-07-04T12:36:00+00:00",
      "type": "snapshot",
      "url": "../manifest/f/1/c6758e1219e212993f5db422100bca4eb68818/1.13-pre6.json"
    }
  ],
  "next": [
    "1.13-pre7"
  ],
  "normalizedVersion": "1.13.0-pre.6",
  "previous": [
    "1.13-pre5"
  ],
  "protocol": {
    "type": "netty",
    "version": 388
  },
  "releaseTarget": "1.13",
  "releaseTime": "2018-07-04T12:36:00+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1512
  }
}

=== skyrising/mc-versions/data/version/1.5.json
{
  "client": true,
  "downloads": {
    "client": {
      "sha1": "a3da981fc9b875a51975d8f8100cc0c201c2ce54",
      "size": 5555731,
      "url": "https://launcher.mojang.com/v1/objects/a3da981fc9b875a51975d8f8100cc0c201c2ce54/client.jar"
    },
    "server": {
      "sha1": "aedad5159ef56d69c5bcf77ed141f53430af43c3",
      "size": 2356736,
      "url": "https://launcher.mojang.com/v1/objects/aedad5159ef56d69c5bcf77ed141f53430af43c3/server.jar"
    },
    "windows_server": {
      "sha1": "6aab93583104a1acfa9b01fd48a10726daf8f011",
      "size": 2537984,
      "url": "https://launcher.mojang.com/v1/objects/6aab93583104a1acfa9b01fd48a10726daf8f011/windows_server.exe"
    }
  },
  "id": "1.5",
  "manifests": [
    {
      "assetHash": "4759bad2824e419da9db32861fcdc3a274336532",
      "assetIndex": "pre-1.6",
      "downloads": "f53ab28ac22b856386221e7f3529a5929e5c872e",
      "downloadsId": 1,
      "hash": "02f461146ce02227a8b6fa2062706580b660d2b3",
      "lastModified": "2019-02-14T15:33:28+00:00",
      "time": "2013-03-06T22:00:00+00:00",
      "type": "snapshot",
      "url": "../manifest/0/2/f461146ce02227a8b6fa2062706580b660d2b3/1.5.json"
    }
  ],
  "next": [
    "13w11a"
  ],
  "normalizedVersion": "1.5.0",
  "previous": [
    "13w10b"
  ],
  "protocol": {
    "type": "modern",
    "version": 60
  },
  "releaseTarget": "1.5",
  "releaseTime": "2013-03-13T00:00:00+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== skyrising/mc-versions/data/version/1.9-pre3.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "81b626ebd0efa06f07b3f0dec1af34989ab61fd0",
      "size": 8698063,
      "url": "https://launcher.mojang.com/v1/objects/81b626ebd0efa06f07b3f0dec1af34989ab61fd0/client.jar"
    },
    "server": {
      "sha1": "db995628b109fd83953ffadb749c2432fac70d9e",
      "size": 8848702,
      "url": "https://launcher.mojang.com/v1/objects/db995628b109fd83953ffadb749c2432fac70d9e/server.jar"
    }
  },
  "id": "1.9-pre3",
  "manifests": [
    {
      "assetHash": "06cc9a2c5ce504dc712ea2f699e4d645c48416dd",
      "assetIndex": "1.9",
      "downloads": "a7c76e1aa9f1924739b1f6c5cd0ae891301185d9",
      "downloadsId": 1,
      "hash": "88d594829c5c30c0b331dba30f3e2bc3b0fbd19e",
      "time": "2016-02-24T15:52:36+00:00",
      "type": "snapshot",
      "url": "../manifest/8/8/d594829c5c30c0b331dba30f3e2bc3b0fbd19e/1.9-pre3.json"
    },
    {
      "assetHash": "06cc9a2c5ce504dc712ea2f699e4d645c48416dd",
      "assetIndex": "1.9",
      "downloads": "a7c76e1aa9f1924739b1f6c5cd0ae891301185d9",
      "downloadsId": 1,
      "hash": "48372c444636d120d1ecce7b327704233973b6b1",
      "time": "2016-02-24T15:52:36+00:00",
      "type": "snapshot",
      "url": "../manifest/4/8/372c444636d120d1ecce7b327704233973b6b1/1.9-pre3.json"
    },
    {
      "assetHash": "06cc9a2c5ce504dc712ea2f699e4d645c48416dd",
      "assetIndex": "1.9",
      "downloads": "a7c76e1aa9f1924739b1f6c5cd0ae891301185d9",
      "downloadsId": 1,
      "hash": "3909edf5d77361cdc8fbab9ed151d1a710c0c323",
      "time": "2016-02-24T15:52:36+00:00",
      "type": "snapshot",
      "url": "../manifest/3/9/09edf5d77361cdc8fbab9ed151d1a710c0c323/1.9-pre3.json"
    }
  ],
  "next": [
    "1.9-pre4"
  ],
  "normalizedVersion": "1.9.0-pre.3",
  "previous": [
    "1.9-pre2"
  ],
  "protocol": {
    "type": "netty",
    "version": 105
  },
  "releaseTarget": "1.9",
  "releaseTime": "2016-02-24T15:52:36+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 167
  }
}
